### PR TITLE
Create currentVersion.txt

### PR DESCRIPTION
**Pull request by gilrosenthal**

### CODE REVIEW

**Comment by KalyanPalepu** [comment]
This is what the readme is for

**Comment by gilrosenthal** [comment]
No. It is not. This is a master file with just the version to keep a
record. Please reconsider.

On Mon, Jan 26, 2015 at 7:55 PM, KingSting notifications@github.com wrote:

> This is what the readme is for
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RLLatinGenerator/LatinGenerator/pull/6#issuecomment-71570811
> .

## 

Much Gil. Very Rosenthal. Such Wow. Doge

**Comment by KalyanPalepu** [comment]
You deleted the pull request, so I can't reopen it anyway

**Comment by Robert-Cunningham** [comment]
Gil had a valid point - this is for the auto updater.

**Pull request closed without merging**
